name: Test

on:
  pull_request:

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo job1

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo job2
